### ISSUE TITLE
Not wait while itunes process app

### ISSUE THREAD

**Issue by aktec** [fastlane/pilot#100]
I use pilot in jenkins, and after ipa is uploaded, pilot several hours wait while itunes processing app.
It hangs my jenkins-slaves. Is it possible to add a key for only uploading ipa and don't wait while itunes process app?
If ipa is uploaded - exit with success. If ipa uploading failed - exit with error.

**Comment by vorobievalex** [comment]
You can use key skip_submission: true (--skip_submission)
Without this key pilot has to wait for the build to be processed to be able to distribute the build to testers.

**Comment by micnguyen** [comment]
I had also left for the submission process to completely finalise in iTunes Connect and even though I can see it processed and ready for download to testers, Pilot does not seem to stop the "Waiting for Processing" outputs.

**Comment by Paulo-Branco** [comment]
@micnguyen I guess that depends on the kind of testers you want to deploy to. iTunes connect will automatically distribute any new build to internal testers if testing is enabled for that particular version / build train. Skip submission only prevents fastlane from sending the build for external testing review. So if you're only targeting internal testers you can pass false to skip_submission and you won't have to wait for the processing to finish.

**Comment by micnguyen** [comment]
@Paulo-Branco We are only submitting to internal testers - so thank you very much for that insight of skip_submission still releasing to internal testers.

**Comment by Paulo-Branco** [comment]
No problem. I've had that question myself. Just make sure you've manually enabled internal testing for that version in iTunes Connect and the rest should work.

**Comment by orta** [comment]
I think it might make sense to do a [check for an interactive shell](https://github.com/fastlane/fastlane_core/blob/feature/messaging/lib/fastlane_core/ui/implementations/shell.rb#L74-L79) when deciding to wait for the iTunes processing?

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1888. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
