### ISSUE TITLE
Processing builds are reported as "expired"

### ISSUE THREAD

**Issue by koenpunt** [fastlane/pilot#115]
Processing builds are incorrectly reported as "expired". Also the build shows up twice in the list.

```
+-----------+---------+----------+----------+----------+
|                    xxxxxxx Builds                    |
+-----------+---------+----------+----------+----------+
| Version # | Build # | Testing  | Installs | Sessions |
+-----------+---------+----------+----------+----------+
| 1.0       | 3       | Expired  | 0        | 0        |
| 1.0       | 4       | Inactive | 2        | 9        |
| 1.0       | 5       | Internal | 1        | 0        |
| 1.0       | 6       | Expired  | 0        | 0        |
| 1.0       | 6       | Expired  | 0        | 0        |
+-----------+---------+----------+----------+----------+
```

![image](https://cloud.githubusercontent.com/assets/351038/12204083/5ffae18a-b632-11e5-89a3-31a954652c1d.png)

**Comment by vpolouchkine** [comment]
Can you share the full log and the version number of pilot?

**Comment by koenpunt** [comment]
This is the full log, except for the "Multiple teams found" question. And I'm using the latest version, 1.2.1

**Comment by ohwutup** [comment]
@koenpunt would you mind sharing the lane in your fastfile that calls pilot?

**Comment by koenpunt** [comment]
@ohwutup nothing fancy there, just `pilot` without arguments

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1883. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:

**Comment by koenpunt** [comment]
You might consider locking conversation of these closed issues :)
