### ISSUE TITLE
Pilot bails out when it takes some time for an uploaded build to appear in iTunes Connect

### ISSUE THREAD

**Issue by petterikamppuririchie** [fastlane/pilot#151]
It seems that it takes some time for iTunes Connect to start showing an uploaded build.

Pilot doesn't seem to like it, and it crashes here:

```
/var/lib/gems/2.0.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:88:in `wait_for_processing_build': [!] undefined method `train_version' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.0.0/gems/pilot-1.4.1/lib/pilot/build_manager.rb:25:in `upload'
	from /var/lib/gems/2.0.0/gems/pilot-1.4.1/lib/pilot/commands_generator.rb:59:in `block (2 levels) in run'
```

I think this happens because there are no builds processing at pilot/_buildmanager.rb line 78 `break if builds.count == 0`.

This breaks the submission part of Pilot.

Has anyone else seen this?

P.S. I'm trying to setup a Linux server to do the uploads (I cannot wait for processing to finish on an expensive Mac machine we have in the cloud). Not very easy :) Really waiting for https://github.com/fastlane/fastlane_core/pull/73/ to be finished, and even after that I'd need a way to customize iTMSTransporter path.

**Comment by vpolouchkine** [comment]
Can you consistently repro this?

**Comment by petterikamppuririchie** [comment]
It consistently crashed/bailed out when the build was not visible in iTunes Connect. Don't know why sometimes the build was not visible in iTunes Connect immediately. So, in a sense, yes, the behavior of the app is there and consistently reproducible, but it depends on iTunes Connect doing things differently sometimes. When it happened, there was about one minute delay from upload before the build was visible in iTunes Connect.

Also, to throw more stuff in this ticket, I'd like to be able to upload and submit for testing separately. This way I could have the Mac build machine do the uploading, and then pass the build number to a Linux machine that would keep polling ITC and handle the submission (as that only requires Spaceship, right? [and not iTMSTransporter]).

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1875. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
