### ISSUE TITLE
Feedback on Pilot from a Sysadmin perspective

### ISSUE THREAD

**Issue by jedi4ever** [fastlane/pilot#22]
We've exchanged some time ago, the fact that I like the functionality of the fastlane tools , but as a sysadmin I dislike the magic. Here I will go through the current ready , function to give feedback:

- pilot will automatically look for an ipa: so what happens when there are more then one? I would agree it would be a nice default, but should not execute immediately unless you override this using a cli flag
- pilot helps shows you the params: there is no way to ask for the specific subcommands params. Adding --help to a subcommand will make it barf
- having env variables to set things is a :+1: 
- bundle identifier magic on the other hand is cool
- pilot upload --skip-submission is unclear, naming should reflect what it means - --upload-and-dont-distribute-to-tester alike would be more clear
- pilot add docs gives not indication if this is an internal or an external user invite
- I would love the feedback in the console during any command which account has executed the task
- pilot export could use a delimiter flag . Believe it or not there are many flavors of csv files
- how is my password store: it mentions credentials Manager but when I click on it , it uses DELIVER_PASSWORD , will that be PILOT_PASSWORD now?
- I don't see where to specify the organization in case of a multi organization member itunes
- I'd love to a list of the exit codes to integrate it in my CI tool

HTH

**Comment by KrauseFx** [comment]
Thank you so much for this valuable feedback! I'll take a closer look at each of your points over the next week.

> I don't see where to specify the organization in case of a multi organization member itunes

Are you talking about when you're in multiple Developer teams? If so, I assume you're talking about the Apple Developer Portal, as iTunes Connect doesn't yet support multiple teams, right?

**Comment by jedi4ever** [comment]
@KrauseFx you are right , that last one doesn't make sense .

**Comment by theodorton** [comment]
@KrauseFx I think iTunes Connect support multiple teams now; I'm part of two teams right now with the same user. Support for a `team_id` argument to `pilot` both in the CLI and through `Fastfile` would be nice :)

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1919. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
