### ISSUE TITLE
Pilot should use Deliverfile user for authentication

### ISSUE THREAD

**Issue by tompowered** [fastlane/pilot#33]
Since iTunes Connect doesn't support multiple teams, I often use one Apple ID to interact with the Dev Center (defined in an Appfile) and another ID for iTunes Connect (defined in a Deliverfile).

Unfortunately `pilot` always tries authenticating with iTunes Connect using the Appfile account (adding `-u` to the command works, but it's not as convenient).

It would be great if `pilot` could use the ID specified in the Deliverfile by default.

**Comment by KrauseFx** [comment]
I don't think that's right. The `Deliverfile` is exclusively for `deliver`. The `Appfile` is shared across all tools. 

The better solution would be to support separate email addresses per platform in the `Appfile`

**Comment by tompowered** [comment]
That works too.

As long as I can define each account email and get both passwords stored in the keychain so I only need to configure it once I'll be happy. :sunglasses:

**Comment by tp** [comment]
Is there a recommended workaround to set the pilot to use the `Deliverfile` from inside the `Fastfile` / `pilot` action? (i.e. a simple way to set the Deliverfile values as environment vars?)

**Comment by vittoriom** [comment]
Following this because I switched from `deliver` to `pilot` after the big iTunes Connect change and following `fastlane` release and now `pilot` asks me for the username. Just had a look at the `Appfile` thing, specified `app_identifier` and `apple_id` there and I get:

```
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.3/lib/gym/detect_values.rb:16:in `set_additional_default_values': No project/workspace found in the current directory. (RuntimeError)
```

**Comment by KrauseFx** [comment]
@vittoriom So the app identifier works, but it can't find your project. You only have to specify your Xcode project using the following options from `pilot --help`

```
    -w, --workspace STRING Path the workspace file (GYM_WORKSPACE)
    -p, --project STRING Path the project file (GYM_PROJECT)
```

**Comment by vittoriom** [comment]
@KrauseFx `gym` is already configured through the `Gymfile`, should I do more steps? Let's say I drop the `Appfile`, is there something like a `Pilotfile`? I just would like to avoid passing all these parameters to the `pilot` steps in the `Fastfile` :(

**Comment by KrauseFx** [comment]
@vittoriom There is so `Pilotfile`, but I could implement it. Would you like to use one?

**Comment by vittoriom** [comment]
It's just what came to my mind when thinking about the configuration. 
I have a `Deliverfile` for `deliver` (even though it's my understanding that other tools also take information from there?), a `Gymfile` for `gym`, and now `pilot` wants to get configuration parameters as well. 
Unless the `Appfile` could work as a `Deliverfile` + `Gymfile` + "`Pilotfile`", I don't see the point in the `Appfile` as of now :O but I'm a bit confused to be honest.
Nevertheless, between passing the parameters to `pilot` in the `Fastfile` and having a separate `Pilotfile`, I would rather have the latter.

**Comment by jimjeffers** [comment]
@KrauseFx I have the same issue here. I have an apple dev account to connect to various teams I'm a part of, but I have separate itunes connect email addresses specific to each team. The Appfile seems to need an apple developer ID and an itunes connect ID (for deliver and pilot). What's the best way to handle this at the moment? I currently do this in the deliver file for deliver. But this seems a bit silly.. it's not that the username is specific to deliver, it's specific to itunes connect vs. the apple developer portal.

**Comment by edwinbosire** [comment]
I have a different account for ***iTunes Connect*** and ***Developer Portal***, to complicate matters, I belong to more than one Team on the developer portal. My solution is as follows (yours could vary)

1. In my `Appfile` I set the following extra parameters `team_name` and `team_id` e.g
```ruby
app_identifier "uk.co.theweek" 
apple_id "developerPortalAccount@mail.co.uk"
team_name "Dennis Publishing Limited"
team_id "B999999QWE"
```
2. In my `Fastfile`, under pilot, I add the username as an extra parameter. Here is an example

```ruby
lane :beta do
    sigh
    pilot(
      username: "iTunesConnectAccount@mail.co.uk",
      ipa: "Builds/The Week UK.ipa",
      skip_submission: true
      )
```

I find that the above works rather well for me.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1916. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
