### ISSUE TITLE
Credential error when password has special characters

### ISSUE THREAD

**Issue by Palleas** [fastlane/pilot#70]
As mentioned on Twitter a few days ago, I was having a credential error when I tried uploading a build to Testflight: 
![csmp7xsu8aatsxh](https://cloud.githubusercontent.com/assets/48797/10883233/82dfbf28-813e-11e5-890c-d49f81386e7f.png)

I tried `rm /tmp/spaceship*` as suggested in #23 without luck and the only thing that worked for me was **changing my password** as it contained special characters like `|` (pipe) and `)` (right parenthesis) so maybe it has something to do with escaping those special chars? It's weird though because `sigh` was able to connect to the member center and fetch provisioning profiles and code signing identities.

Let me know if I can provide more informations!

**Comment by KrauseFx** [comment]
Easiest way is to change the password to not include special characters.

**Comment by Palleas** [comment]
That's what I did but that's confusing so I suggested some additional informations in #71.

**Comment by Domsware** [comment]
Easiest way but definitely not the best.

**Comment by micnguyen** [comment]
Changing password is certainly the easiest - but what is the root cause of this?

**Comment by KrauseFx** [comment]
@micnguyen If we knew, this would be fixed :wink: Probably has something to do with escaping some special characters.

**Comment by hhanesand** [comment]
@KrauseFx Can confirm I'm having this issue with a password containing `|`, `[`, `#`, `]`,  and `)`.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1901. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
