### ISSUE TITLE
unable to deploy with pilot - getting strange "train" error

### ISSUE THREAD

**Issue by edwardvalentini** [fastlane/pilot#82]
I get this error when I try to use pilot to testflight an app.. this is my crash reference number `46c8b45a6fadb95d287e7d06d2793032`

```
[14:23:43]: This train could not be activated because the build(s) is not set expiration date properly.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | update_fastlane                     | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | increment_build_number              | 2           |
| 5    | increment_version_number            | 1           |
| 6    | gym                                 | 224         |
| 7    | commit_version_bump                 | 1           |
| 8    | push_to_git_remote                  | 3           |
| 9    | pilot                               | 2527        |
+------+-------------------------------------+-------------+

[14:23:44]: fastlane finished with errors
Successfully submitted crash report. If this is a problem with one of the tools you want to report
please submit an issue on GitHub and attach the following number to it: '46c8b45a6fadb95d287e7d06d2793032'
```

**Comment by sharky101** [comment]
Also getting this.

**Comment by bassrock** [comment]
Also getting this one that may be related: "You cannot activate more than one train for the same platform." However the build does appear in iTunes connect: 4af330868104d661c41034a58be09376

**Comment by edwardvalentini** [comment]
For me too the builds appear on itunesConnect.. its just that it doesnt automatically push the testflight to users.

**Comment by JonSnippets** [comment]
seeing the same thing. crash ref. number is 10f3327b6c781dd5de12315adf099a8e

**Comment by KrauseFx** [comment]
Weird, same error over there https://github.com/fastlane/spaceship/issues/175

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1898. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
