### ISSUE TITLE
Old version stuck on processing makes 'Waiting for iTunes Connect to process new build' wait forever

### ISSUE THREAD

**Issue by kerrmarin** [fastlane/pilot#97]
Hi there,

I have an app that has older versions that are stuck on "processing" and they have been for a few days now. This means that Pilot will keep waiting and waiting even though the current version has processed correctly. It would be great if Pilot only waited for builds of the current version, or even better, if it only waited for the specific build and version that was uploaded.

Thanks

**Comment by kerrmarin** [comment]
I think this issue is potentially fixed by https://github.com/fastlane/pilot/pull/75

**Comment by Paulo-Branco** [comment]
I'm getting this behaviour even without any version stuck on processing. The funny thing is that watchbuild returns the build status correctly (aka triggers a notification when it ends processing), but pilot keeps waiting forever. Eventually it fails, which prevents it from both setting the changelog and running the next actions in the fastlane file.

**Comment by micnguyen** [comment]
I too am having this issue of Pilot reporting that it is waiting for iTunes to process the build (even though iTunes Connect has finished processing the latest build). 

@Paulo-Branco That's a shame. For us, the IPA deploy is our very last fastlane step so the halted iTunes Connect Processing is fine for our case. The issue of setting the changelog though is a worry... would be great for this to get fixed. Anyone have any ideas?

**Comment by katunch** [comment]
Same here with `pilot 1.2.0`

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1889. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
